### ISSUE TITLE
Slider is lagging

### ISSUE THREAD

**Issue by daudix** [lovasoa/gnome-keyboard-backlight-menu#4]
Slider is lagging while you scroll over it 

![Slider-Broken](https://user-images.githubusercontent.com/77155297/165644009-a11a95f3-a1e2-458a-8ab9-cdfc14f7a6a9.gif)

**Comment by lovasoa** [comment]
It's a feature, not a bug. If your hardware does not support more than a few levels of brightness, then the slider position will be "rounded" to the closest level supported by your hardware.

**Comment by daudix** [comment]
This is not a feature, on mac these is 255 backlight levels, so this is issue

**Comment by lovasoa** [comment]
Oh, I see. If your hardware has more brightness levels and upower does not expose all of them, then you should open an issue with upower.

**Comment by lovasoa** [comment]
https://upower.freedesktop.org/
