### ISSUE TITLE
How to set keyboard shortcut?

### ISSUE THREAD

**Issue by Apacelus** [lovasoa/gnome-keyboard-backlight-menu#5]
What is the command, so I could set a keyboard shortcut for this? I cant figure out how to talk to dbus...

**Comment by lovasoa** [comment]
Hello ! This extension is just a GUI for talking to gnome. If you would like to have a shortcut to change screen brightness, you should open an issue directly to gnome.

**Comment by Apacelus** [comment]
I was just wondering if you knew what the dbus call is? I wanted to make my own shortcut, I wasnt asking for you to implement it in your project

**Comment by brendangreenley** [comment]
> I was just wondering if you knew what the dbus call is? I wanted to make my own shortcut, I wasnt asking for you to implement it in your project

```
gdbus call --session --dest org.gnome.SettingsDaemon.Power --object-path /org/gnome/SettingsDaemon/Power --method org.gnome.SettingsDaemon.Power.Keyboard.StepDown
```

```
gdbus call --session --dest org.gnome.SettingsDaemon.Power --object-path /org/gnome/SettingsDaemon/Power --method org.gnome.SettingsDaemon.Power.Keyboard.StepUp
```
